CREATE TABLE IF NOT EXISTS genres (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar(200),
    release_date date,
    duration int,
    mpa_id int NOT NULL,
    FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int NOT NULL,
    genre_id int NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (film_id),
    FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar NOT NULL,
    name varchar,
    email varchar NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id int NOT NULL,
    friend_id int NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (friend_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id int NOT NULL,
    film_id int NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id)
);